/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard.settings.index'
import { Route as DashboardSeoIndexRouteImport } from './routes/dashboard.seo.index'
import { Route as DashboardProductsIndexRouteImport } from './routes/dashboard.products.index'
import { Route as DashboardEnquiriesIndexRouteImport } from './routes/dashboard.enquiries.index'
import { Route as DashboardContentIndexRouteImport } from './routes/dashboard.content.index'
import { Route as DashboardConsignmentsIndexRouteImport } from './routes/dashboard.consignments.index'
import { Route as DashboardCategoriesIndexRouteImport } from './routes/dashboard.categories.index'
import { Route as DashboardAgeRangesIndexRouteImport } from './routes/dashboard.age-ranges.index'
import { Route as DashboardSettingsAdminUsersRouteImport } from './routes/dashboard.settings.admin-users'
import { Route as DashboardSeoSitemapRouteImport } from './routes/dashboard.seo.sitemap'
import { Route as DashboardSeoRedirectsRouteImport } from './routes/dashboard.seo.redirects'
import { Route as DashboardSeoProductsRouteImport } from './routes/dashboard.seo.products'
import { Route as DashboardSeoPagesRouteImport } from './routes/dashboard.seo.pages'
import { Route as DashboardSeoGlobalRouteImport } from './routes/dashboard.seo.global'
import { Route as DashboardSeoCategoriesRouteImport } from './routes/dashboard.seo.categories'
import { Route as DashboardProductsCreateRouteImport } from './routes/dashboard.products.create'
import { Route as DashboardProductsIdRouteImport } from './routes/dashboard.products.$id'
import { Route as DashboardEnquiriesIdRouteImport } from './routes/dashboard.enquiries.$id'
import { Route as DashboardContentHomepageRouteImport } from './routes/dashboard.content.homepage'
import { Route as DashboardConsignmentsIdRouteImport } from './routes/dashboard.consignments.$id'
import { Route as DashboardCategoriesIdRouteImport } from './routes/dashboard.categories.$id'
import { Route as DashboardContentPagesIndexRouteImport } from './routes/dashboard.content.pages.index'
import { Route as DashboardContentPagesSlugRouteImport } from './routes/dashboard.content.pages.$slug'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSeoIndexRoute = DashboardSeoIndexRouteImport.update({
  id: '/seo/',
  path: '/seo/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsIndexRoute = DashboardProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEnquiriesIndexRoute = DashboardEnquiriesIndexRouteImport.update({
  id: '/enquiries/',
  path: '/enquiries/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContentIndexRoute = DashboardContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConsignmentsIndexRoute =
  DashboardConsignmentsIndexRouteImport.update({
    id: '/consignments/',
    path: '/consignments/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCategoriesIndexRoute =
  DashboardCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgeRangesIndexRoute = DashboardAgeRangesIndexRouteImport.update({
  id: '/age-ranges/',
  path: '/age-ranges/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsAdminUsersRoute =
  DashboardSettingsAdminUsersRouteImport.update({
    id: '/settings/admin-users',
    path: '/settings/admin-users',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSeoSitemapRoute = DashboardSeoSitemapRouteImport.update({
  id: '/seo/sitemap',
  path: '/seo/sitemap',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSeoRedirectsRoute = DashboardSeoRedirectsRouteImport.update({
  id: '/seo/redirects',
  path: '/seo/redirects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSeoProductsRoute = DashboardSeoProductsRouteImport.update({
  id: '/seo/products',
  path: '/seo/products',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSeoPagesRoute = DashboardSeoPagesRouteImport.update({
  id: '/seo/pages',
  path: '/seo/pages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSeoGlobalRoute = DashboardSeoGlobalRouteImport.update({
  id: '/seo/global',
  path: '/seo/global',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSeoCategoriesRoute = DashboardSeoCategoriesRouteImport.update({
  id: '/seo/categories',
  path: '/seo/categories',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsCreateRoute = DashboardProductsCreateRouteImport.update({
  id: '/products/create',
  path: '/products/create',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsIdRoute = DashboardProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEnquiriesIdRoute = DashboardEnquiriesIdRouteImport.update({
  id: '/enquiries/$id',
  path: '/enquiries/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContentHomepageRoute =
  DashboardContentHomepageRouteImport.update({
    id: '/content/homepage',
    path: '/content/homepage',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardConsignmentsIdRoute = DashboardConsignmentsIdRouteImport.update({
  id: '/consignments/$id',
  path: '/consignments/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCategoriesIdRoute = DashboardCategoriesIdRouteImport.update({
  id: '/categories/$id',
  path: '/categories/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContentPagesIndexRoute =
  DashboardContentPagesIndexRouteImport.update({
    id: '/content/pages/',
    path: '/content/pages/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardContentPagesSlugRoute =
  DashboardContentPagesSlugRouteImport.update({
    id: '/content/pages/$slug',
    path: '/content/pages/$slug',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/categories/$id': typeof DashboardCategoriesIdRoute
  '/dashboard/consignments/$id': typeof DashboardConsignmentsIdRoute
  '/dashboard/content/homepage': typeof DashboardContentHomepageRoute
  '/dashboard/enquiries/$id': typeof DashboardEnquiriesIdRoute
  '/dashboard/products/$id': typeof DashboardProductsIdRoute
  '/dashboard/products/create': typeof DashboardProductsCreateRoute
  '/dashboard/seo/categories': typeof DashboardSeoCategoriesRoute
  '/dashboard/seo/global': typeof DashboardSeoGlobalRoute
  '/dashboard/seo/pages': typeof DashboardSeoPagesRoute
  '/dashboard/seo/products': typeof DashboardSeoProductsRoute
  '/dashboard/seo/redirects': typeof DashboardSeoRedirectsRoute
  '/dashboard/seo/sitemap': typeof DashboardSeoSitemapRoute
  '/dashboard/settings/admin-users': typeof DashboardSettingsAdminUsersRoute
  '/dashboard/age-ranges/': typeof DashboardAgeRangesIndexRoute
  '/dashboard/categories/': typeof DashboardCategoriesIndexRoute
  '/dashboard/consignments/': typeof DashboardConsignmentsIndexRoute
  '/dashboard/content/': typeof DashboardContentIndexRoute
  '/dashboard/enquiries/': typeof DashboardEnquiriesIndexRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
  '/dashboard/seo/': typeof DashboardSeoIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/content/pages/$slug': typeof DashboardContentPagesSlugRoute
  '/dashboard/content/pages/': typeof DashboardContentPagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/categories/$id': typeof DashboardCategoriesIdRoute
  '/dashboard/consignments/$id': typeof DashboardConsignmentsIdRoute
  '/dashboard/content/homepage': typeof DashboardContentHomepageRoute
  '/dashboard/enquiries/$id': typeof DashboardEnquiriesIdRoute
  '/dashboard/products/$id': typeof DashboardProductsIdRoute
  '/dashboard/products/create': typeof DashboardProductsCreateRoute
  '/dashboard/seo/categories': typeof DashboardSeoCategoriesRoute
  '/dashboard/seo/global': typeof DashboardSeoGlobalRoute
  '/dashboard/seo/pages': typeof DashboardSeoPagesRoute
  '/dashboard/seo/products': typeof DashboardSeoProductsRoute
  '/dashboard/seo/redirects': typeof DashboardSeoRedirectsRoute
  '/dashboard/seo/sitemap': typeof DashboardSeoSitemapRoute
  '/dashboard/settings/admin-users': typeof DashboardSettingsAdminUsersRoute
  '/dashboard/age-ranges': typeof DashboardAgeRangesIndexRoute
  '/dashboard/categories': typeof DashboardCategoriesIndexRoute
  '/dashboard/consignments': typeof DashboardConsignmentsIndexRoute
  '/dashboard/content': typeof DashboardContentIndexRoute
  '/dashboard/enquiries': typeof DashboardEnquiriesIndexRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
  '/dashboard/seo': typeof DashboardSeoIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/content/pages/$slug': typeof DashboardContentPagesSlugRoute
  '/dashboard/content/pages': typeof DashboardContentPagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/categories/$id': typeof DashboardCategoriesIdRoute
  '/dashboard/consignments/$id': typeof DashboardConsignmentsIdRoute
  '/dashboard/content/homepage': typeof DashboardContentHomepageRoute
  '/dashboard/enquiries/$id': typeof DashboardEnquiriesIdRoute
  '/dashboard/products/$id': typeof DashboardProductsIdRoute
  '/dashboard/products/create': typeof DashboardProductsCreateRoute
  '/dashboard/seo/categories': typeof DashboardSeoCategoriesRoute
  '/dashboard/seo/global': typeof DashboardSeoGlobalRoute
  '/dashboard/seo/pages': typeof DashboardSeoPagesRoute
  '/dashboard/seo/products': typeof DashboardSeoProductsRoute
  '/dashboard/seo/redirects': typeof DashboardSeoRedirectsRoute
  '/dashboard/seo/sitemap': typeof DashboardSeoSitemapRoute
  '/dashboard/settings/admin-users': typeof DashboardSettingsAdminUsersRoute
  '/dashboard/age-ranges/': typeof DashboardAgeRangesIndexRoute
  '/dashboard/categories/': typeof DashboardCategoriesIndexRoute
  '/dashboard/consignments/': typeof DashboardConsignmentsIndexRoute
  '/dashboard/content/': typeof DashboardContentIndexRoute
  '/dashboard/enquiries/': typeof DashboardEnquiriesIndexRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
  '/dashboard/seo/': typeof DashboardSeoIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/content/pages/$slug': typeof DashboardContentPagesSlugRoute
  '/dashboard/content/pages/': typeof DashboardContentPagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/'
    | '/dashboard/categories/$id'
    | '/dashboard/consignments/$id'
    | '/dashboard/content/homepage'
    | '/dashboard/enquiries/$id'
    | '/dashboard/products/$id'
    | '/dashboard/products/create'
    | '/dashboard/seo/categories'
    | '/dashboard/seo/global'
    | '/dashboard/seo/pages'
    | '/dashboard/seo/products'
    | '/dashboard/seo/redirects'
    | '/dashboard/seo/sitemap'
    | '/dashboard/settings/admin-users'
    | '/dashboard/age-ranges/'
    | '/dashboard/categories/'
    | '/dashboard/consignments/'
    | '/dashboard/content/'
    | '/dashboard/enquiries/'
    | '/dashboard/products/'
    | '/dashboard/seo/'
    | '/dashboard/settings/'
    | '/dashboard/content/pages/$slug'
    | '/dashboard/content/pages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/categories/$id'
    | '/dashboard/consignments/$id'
    | '/dashboard/content/homepage'
    | '/dashboard/enquiries/$id'
    | '/dashboard/products/$id'
    | '/dashboard/products/create'
    | '/dashboard/seo/categories'
    | '/dashboard/seo/global'
    | '/dashboard/seo/pages'
    | '/dashboard/seo/products'
    | '/dashboard/seo/redirects'
    | '/dashboard/seo/sitemap'
    | '/dashboard/settings/admin-users'
    | '/dashboard/age-ranges'
    | '/dashboard/categories'
    | '/dashboard/consignments'
    | '/dashboard/content'
    | '/dashboard/enquiries'
    | '/dashboard/products'
    | '/dashboard/seo'
    | '/dashboard/settings'
    | '/dashboard/content/pages/$slug'
    | '/dashboard/content/pages'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/'
    | '/dashboard/categories/$id'
    | '/dashboard/consignments/$id'
    | '/dashboard/content/homepage'
    | '/dashboard/enquiries/$id'
    | '/dashboard/products/$id'
    | '/dashboard/products/create'
    | '/dashboard/seo/categories'
    | '/dashboard/seo/global'
    | '/dashboard/seo/pages'
    | '/dashboard/seo/products'
    | '/dashboard/seo/redirects'
    | '/dashboard/seo/sitemap'
    | '/dashboard/settings/admin-users'
    | '/dashboard/age-ranges/'
    | '/dashboard/categories/'
    | '/dashboard/consignments/'
    | '/dashboard/content/'
    | '/dashboard/enquiries/'
    | '/dashboard/products/'
    | '/dashboard/seo/'
    | '/dashboard/settings/'
    | '/dashboard/content/pages/$slug'
    | '/dashboard/content/pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/seo/': {
      id: '/dashboard/seo/'
      path: '/seo'
      fullPath: '/dashboard/seo/'
      preLoaderRoute: typeof DashboardSeoIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/': {
      id: '/dashboard/products/'
      path: '/products'
      fullPath: '/dashboard/products/'
      preLoaderRoute: typeof DashboardProductsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/enquiries/': {
      id: '/dashboard/enquiries/'
      path: '/enquiries'
      fullPath: '/dashboard/enquiries/'
      preLoaderRoute: typeof DashboardEnquiriesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/content/': {
      id: '/dashboard/content/'
      path: '/content'
      fullPath: '/dashboard/content/'
      preLoaderRoute: typeof DashboardContentIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/consignments/': {
      id: '/dashboard/consignments/'
      path: '/consignments'
      fullPath: '/dashboard/consignments/'
      preLoaderRoute: typeof DashboardConsignmentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categories/': {
      id: '/dashboard/categories/'
      path: '/categories'
      fullPath: '/dashboard/categories/'
      preLoaderRoute: typeof DashboardCategoriesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/age-ranges/': {
      id: '/dashboard/age-ranges/'
      path: '/age-ranges'
      fullPath: '/dashboard/age-ranges/'
      preLoaderRoute: typeof DashboardAgeRangesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/admin-users': {
      id: '/dashboard/settings/admin-users'
      path: '/settings/admin-users'
      fullPath: '/dashboard/settings/admin-users'
      preLoaderRoute: typeof DashboardSettingsAdminUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/seo/sitemap': {
      id: '/dashboard/seo/sitemap'
      path: '/seo/sitemap'
      fullPath: '/dashboard/seo/sitemap'
      preLoaderRoute: typeof DashboardSeoSitemapRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/seo/redirects': {
      id: '/dashboard/seo/redirects'
      path: '/seo/redirects'
      fullPath: '/dashboard/seo/redirects'
      preLoaderRoute: typeof DashboardSeoRedirectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/seo/products': {
      id: '/dashboard/seo/products'
      path: '/seo/products'
      fullPath: '/dashboard/seo/products'
      preLoaderRoute: typeof DashboardSeoProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/seo/pages': {
      id: '/dashboard/seo/pages'
      path: '/seo/pages'
      fullPath: '/dashboard/seo/pages'
      preLoaderRoute: typeof DashboardSeoPagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/seo/global': {
      id: '/dashboard/seo/global'
      path: '/seo/global'
      fullPath: '/dashboard/seo/global'
      preLoaderRoute: typeof DashboardSeoGlobalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/seo/categories': {
      id: '/dashboard/seo/categories'
      path: '/seo/categories'
      fullPath: '/dashboard/seo/categories'
      preLoaderRoute: typeof DashboardSeoCategoriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/create': {
      id: '/dashboard/products/create'
      path: '/products/create'
      fullPath: '/dashboard/products/create'
      preLoaderRoute: typeof DashboardProductsCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/$id': {
      id: '/dashboard/products/$id'
      path: '/products/$id'
      fullPath: '/dashboard/products/$id'
      preLoaderRoute: typeof DashboardProductsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/enquiries/$id': {
      id: '/dashboard/enquiries/$id'
      path: '/enquiries/$id'
      fullPath: '/dashboard/enquiries/$id'
      preLoaderRoute: typeof DashboardEnquiriesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/content/homepage': {
      id: '/dashboard/content/homepage'
      path: '/content/homepage'
      fullPath: '/dashboard/content/homepage'
      preLoaderRoute: typeof DashboardContentHomepageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/consignments/$id': {
      id: '/dashboard/consignments/$id'
      path: '/consignments/$id'
      fullPath: '/dashboard/consignments/$id'
      preLoaderRoute: typeof DashboardConsignmentsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categories/$id': {
      id: '/dashboard/categories/$id'
      path: '/categories/$id'
      fullPath: '/dashboard/categories/$id'
      preLoaderRoute: typeof DashboardCategoriesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/content/pages/': {
      id: '/dashboard/content/pages/'
      path: '/content/pages'
      fullPath: '/dashboard/content/pages/'
      preLoaderRoute: typeof DashboardContentPagesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/content/pages/$slug': {
      id: '/dashboard/content/pages/$slug'
      path: '/content/pages/$slug'
      fullPath: '/dashboard/content/pages/$slug'
      preLoaderRoute: typeof DashboardContentPagesSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCategoriesIdRoute: typeof DashboardCategoriesIdRoute
  DashboardConsignmentsIdRoute: typeof DashboardConsignmentsIdRoute
  DashboardContentHomepageRoute: typeof DashboardContentHomepageRoute
  DashboardEnquiriesIdRoute: typeof DashboardEnquiriesIdRoute
  DashboardProductsIdRoute: typeof DashboardProductsIdRoute
  DashboardProductsCreateRoute: typeof DashboardProductsCreateRoute
  DashboardSeoCategoriesRoute: typeof DashboardSeoCategoriesRoute
  DashboardSeoGlobalRoute: typeof DashboardSeoGlobalRoute
  DashboardSeoPagesRoute: typeof DashboardSeoPagesRoute
  DashboardSeoProductsRoute: typeof DashboardSeoProductsRoute
  DashboardSeoRedirectsRoute: typeof DashboardSeoRedirectsRoute
  DashboardSeoSitemapRoute: typeof DashboardSeoSitemapRoute
  DashboardSettingsAdminUsersRoute: typeof DashboardSettingsAdminUsersRoute
  DashboardAgeRangesIndexRoute: typeof DashboardAgeRangesIndexRoute
  DashboardCategoriesIndexRoute: typeof DashboardCategoriesIndexRoute
  DashboardConsignmentsIndexRoute: typeof DashboardConsignmentsIndexRoute
  DashboardContentIndexRoute: typeof DashboardContentIndexRoute
  DashboardEnquiriesIndexRoute: typeof DashboardEnquiriesIndexRoute
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute
  DashboardSeoIndexRoute: typeof DashboardSeoIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardContentPagesSlugRoute: typeof DashboardContentPagesSlugRoute
  DashboardContentPagesIndexRoute: typeof DashboardContentPagesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCategoriesIdRoute: DashboardCategoriesIdRoute,
  DashboardConsignmentsIdRoute: DashboardConsignmentsIdRoute,
  DashboardContentHomepageRoute: DashboardContentHomepageRoute,
  DashboardEnquiriesIdRoute: DashboardEnquiriesIdRoute,
  DashboardProductsIdRoute: DashboardProductsIdRoute,
  DashboardProductsCreateRoute: DashboardProductsCreateRoute,
  DashboardSeoCategoriesRoute: DashboardSeoCategoriesRoute,
  DashboardSeoGlobalRoute: DashboardSeoGlobalRoute,
  DashboardSeoPagesRoute: DashboardSeoPagesRoute,
  DashboardSeoProductsRoute: DashboardSeoProductsRoute,
  DashboardSeoRedirectsRoute: DashboardSeoRedirectsRoute,
  DashboardSeoSitemapRoute: DashboardSeoSitemapRoute,
  DashboardSettingsAdminUsersRoute: DashboardSettingsAdminUsersRoute,
  DashboardAgeRangesIndexRoute: DashboardAgeRangesIndexRoute,
  DashboardCategoriesIndexRoute: DashboardCategoriesIndexRoute,
  DashboardConsignmentsIndexRoute: DashboardConsignmentsIndexRoute,
  DashboardContentIndexRoute: DashboardContentIndexRoute,
  DashboardEnquiriesIndexRoute: DashboardEnquiriesIndexRoute,
  DashboardProductsIndexRoute: DashboardProductsIndexRoute,
  DashboardSeoIndexRoute: DashboardSeoIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardContentPagesSlugRoute: DashboardContentPagesSlugRoute,
  DashboardContentPagesIndexRoute: DashboardContentPagesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
